services:
  app:
    build:
      context: .
    command: sh -c "npx prisma db push && yarn start:prod"
    ports:
      - '4004:4000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
  postgres:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    env_file:
      - .env
    ports:
      - '5436:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}']
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  postgres_data:
